# Generated by Django 2.2.5 on 2019-09-11 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='user_id',
            new_name='user',
        ),
    ]
